# Generated by Django 3.2.3 on 2021-05-25 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Permanent', 'permanent'), ('6 Months', '6 months'), ('1 Year', '1 year')], max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Contracts',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Remote', 'remote'), ('Overseas', 'overseas'), ('Cork', 'cork'), ('Galway', 'galway'), ('Dublin', 'dublin')], max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Full Time', 'full time'), ('Part Time', 'part time'), ('20 Hours', '20 hours')], max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Schedules',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=254)),
                ('description', models.TextField()),
                ('job_contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.contract')),
                ('job_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.location')),
                ('job_schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.schedule')),
            ],
        ),
    ]
