# Generated by Django 3.2.3 on 2021-06-18 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20210615_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='jobs.contract'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='jobs.location'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='jobs.schedule'),
        ),
    ]
