# Generated by Django 3.2.3 on 2021-06-21 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20210618_0757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_contract',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_location',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_schedule',
        ),
        migrations.AddField(
            model_name='job',
            name='contract',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='job',
            name='schedule',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
