# Generated by Django 3.2.3 on 2021-06-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20210622_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='url',
            field=models.CharField(default='', max_length=40),
        ),
    ]
